// productData is an array of several productGroups, which has a name, room and contains an array of products
// These products contain a value for embodiedEnergy, embodiedCO2 and a category (1-5)

const productData = 
[
  {'Name': 'Douche',
  'Room' : 'Bathroom',
  'Products':[
  {EmbodiedEnergy: 100,
   EmbodiedCO2: 2,
  Category: 3},
{EmbodiedEnergy: 80,
   EmbodiedCO2: 2,
Category: 2},
{EmbodiedEnergy: 80,
   EmbodiedCO2: 2,
  Category: 4},
]},
  {'Name': 'Wastafel',
  'Products':[
  {EmbodiedEnergy: 100,
   EmbodiedCO2: 3,
  Category: 2},
{EmbodiedEnergy: 80,
   EmbodiedCO2: 2,
Category: 3},
{EmbodiedEnergy: 80,
   EmbodiedCO2: 2,
  Category: 5},
]},
{'Name': 'Stoel',
'Products':[
{EmbodiedEnergy: 100,
 EmbodiedCO2: 3,
Category: 1},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 3},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 5},
]},
{'Name': 'Bed',
'Products':[
{EmbodiedEnergy: 100,
 EmbodiedCO2: 3,
Category: 1},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 3},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 5},
]},
{'Name': 'Deur',
'Products':[
{EmbodiedEnergy: 100,
 EmbodiedCO2: 3,
Category: 1},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 3},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 5},
]},
{'Name': 'Stoel2345',
'Products':[
{EmbodiedEnergy: 100,
 EmbodiedCO2: 3,
Category: 2},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 3},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 5},
]},
{'Name': 'Dakgoot',
'Products':[
{EmbodiedEnergy: 100,
 EmbodiedCO2: 3,
Category: 2},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 3},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 5},
]},
{'Name': 'Hondenmand',
'Products':[
{EmbodiedEnergy: 100,
 EmbodiedCO2: 3,
Category: 2},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 3},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 5},
]},
{'Name': 'Kippenhok',
'Products':[
{EmbodiedEnergy: 100,
 EmbodiedCO2: 3,
Category: 1},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 3},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 5},
]},
{'Name': 'Tuinkabouter',
'Products':[
{EmbodiedEnergy: 100,
 EmbodiedCO2: 3,
Category: 1},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 3},
{EmbodiedEnergy: 80,
 EmbodiedCO2: 2,
Category: 5},
]}

];

module.exports = productData;